services:
  frontend:
    build: front-end
    ports:
      - "3000:3000"
    volumes:
      - ./front-end:/app
      - /app/node_modules
    env_file:
      - ./front-end/.env
    # environment:
      # REACT_APP_BACKEND_URL: ${REACT_APP_BACKEND_URL}
    develop:
      watch:
        - action: rebuild
          path: ./front-end
          target: /app
          ignore:
            - node_modules/
    networks:
      - mern
  backend:
    build: backend
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    # environment:
    #   - MONGO_URI=${MONGO_URI}
    #   - PORT=${PORT}
    #   - JWT_SECRET=${JWT_SECRET} 
    #   - ALLOWED_ORIGINS=${ALLOWED_ORIGINS}
    #   - CLOUDINARY_CLOUD_NAME=${CLOUDINARY_CLOUD_NAME}
    #   - CLOUDINARY_API_KEY=${CLOUDINARY_API_KEY}
    #   - CLOUDINARY_API_SECRET=${CLOUDINARY_API_SECRET}
    develop:
      watch:
        - action: rebuild
          path: ./backend
          target: /app
          ignore:
            - node_modules/
    networks:
      - mern
    depends_on:
      - mongo
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - mern
networks:
  mern:
    driver: bridge
